Remove driver level PIO initialization
hafs-community/NEMS pull request #3
Opened 2021-03-08 21:39 UTC by uturuncoglu

This PR aims to remove the modifications that was done previously to bring PIO initialization to NEMS driver. Since both CMEPS (https://github.com/hafs-community/CMEPS/pull/1) and CDEPS (https://github.com/hafs-community/CDEPS/pull/2) are modified to have component level PIO initialization, there is no need to keep those modifications in the NEMS level.

Tests:
- Full RTs were run without any problem and passed.

2021-03-10 01:55 UTC, BinLiu-NOAA approved these changes
Looks good to me.

2021-03-10 14:21 UTC, BinLiu-NOAA commented
@uturuncoglu In order to not break the support/HAFS branch at the model level, please hold this PR so that it goes back into the support/HAFS branch together with the following PRs:
hafs-community/ufs-weather-model#8
hafs-community/CMEPS#1
hafs-community/CDEPS#2

2021-03-10 16:23 UTC, uturuncoglu commented
@BinLiu-NOAA sure. I am waiting for your approval.

2021-03-15 16:01 UTC, danrosen25 requested changes
I suggest cleaning up a few hanging variables before approving.

2021-03-15 16:01 UTC, danrosen25 commented on src/MAIN_NEMS.F90
> -      COMM_WORLD = MPI_COMM_WORLD
Please remove line 121 if no longer needed. INTEGER :: COMM_WORLD

2021-03-15 16:01 UTC, danrosen25 commented on src/module_EARTH_GRID_COMP.F90
> -        call ESMF_VMGet(vm, mpiCommunicator=Global_Comm, rc=rc)
VM is no longer needed. See lines
- [ ] 3407
- [ ] 3426
- [ ] 4576

2021-06-09 21:06 UTC, uturuncoglu commented
@BinLiu-NOAA @danrosen25 i am closing this PR because this branch is outdated and I need to work again. I'll create another branch for CDEPS sync and make PR again. Then we could clean the unused branches.

2021-06-09 21:06 UTC, closed without merging